## Chargement des données depuis un fichier CSV

Dans cette étape nous chargeons un dataset au format **CSV** contenant des informations sur les performances des étudiants.

La bibliothèque **Pandas** est utilisée pour lire le fichier et convertir les données en **DataFrame**.

Actions réalisées dans la cellule suivante :

- import de la bibliothèque Pandas
- définition du chemin vers le fichier CSV
- lecture du fichier avec `pd.read_csv()`
- affichage des premières lignes du dataset

In [ ]:
import pandas as pd
# 1. Chargement du fichier
path = "../data/student_data.csv"
df = pd.read_csv(path)
df.head(2)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6

## Aperçu des données

Après le chargement du fichier CSV, il est important de vérifier que les données ont été correctement importées.

Dans cette étape nous affichons les premières lignes du dataset afin d'obtenir un aperçu général des variables présentes dans les données.

In [ ]:
# 2. Chargement du fichier 
path = "../data/student-mat.csv"
df = pd.read_csv(path, sep=';')
# 3. Affichage des 5 premieres lignes
print("Apercu des donnees:")
display(df.head())

Apercu des donnees:

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

## Analyse de la structure du dataset

Pour mieux comprendre la structure des données, nous utilisons la fonction `info()` de Pandas.

Cette fonction permet d'afficher :

- le nombre total de lignes
- les noms des colonnes
- le type de données de chaque colonne
- la présence éventuelle de valeurs manquantes

Cette étape est essentielle avant toute analyse de données.

In [ ]:
# 4. Verification de la structure
print("\nInformations␣sur␣le␣dataset␣:")
df.info()

Informations␣sur␣le␣dataset␣:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

## Chargement d'un dataset JSON

Dans cette section nous manipulons des données **semi-structurées** au format JSON.

Les fichiers JSON sont très utilisés pour stocker ou échanger des données dans les applications web.

Actions réalisées :

- lecture du fichier JSON
- conversion des données en DataFrame Pandas
- affichage des premières lignes pour vérifier le contenu

Manipulation de formats semi-structurés(JSON&EXCEL)

In [ ]:
# chargement du fichier
import pandas as pd
path_json = "../data/movies.json"
df_json=pd.read_json(path_json, lines=True)
display(df_json.head())

,_id,rating,movie_id,description,language,released,rating_cnt,writer,director,cast,img_src,genre,inserted,name
0,{'$oid': '581994c40ad09b0701a0e727'},7.9,tt5286444,Neerja is the story of the courageous Neerja B...,[Hindi],{'$date': '2016-02-19T05:30:00.000+0530'},0,"[Saiwyn Quadras, Sanyukta Shaikh Chawla]",[Ram Madhvani],"[Sonam Kapoor, Shabana Azmi, Yogendra Tikku, A...",https://images-na.ssl-images-amazon.com/images...,"[Biography, Drama, Thriller]",{'$date': '2016-11-02T18:24:52.889+0530'},Neerja
1,{'$oid': '581994c40ad09b0701a0e728'},7.9,tt4434004,A story that revolves around drug abuse in the...,"[Hindi, Panjabi]",{'$date': '2016-06-17T05:30:00.000+0530'},0,"[Sudip Sharma, Abhishek Chaubey]",[Abhishek Chaubey],"[Alia Bhatt, Shahid Kapoor, Diljit Dosanjh, Ka...",https://images-na.ssl-images-amazon.com/images...,"[Crime, Drama, Thriller]",{'$date': '2016-11-02T18:24:52.938+0530'},Udta Punjab
2,{'$oid': '581994c50ad09b0701a0e729'},7.5,tt0248126,Yashvardhan Raichand lives a very wealthy life...,"[Hindi, English, Urdu]",{'$date': '2001-12-14T05:30:00.000+0530'},0,"[Karan Johar, Sheena Parikh]",[Karan Johar],"[Amitabh Bachchan, Jaya Bhaduri, Shah Rukh Kha...",https://images-na.ssl-images-amazon.com/images...,"[Drama, Musical, Romance]",{'$date': '2016-11-02T18:24:53.046+0530'},Kabhi Khushi Kabhie Gham...
3,{'$oid': '581994c50ad09b0701a0e72a'},8.0,tt0347304,"Naina, an introverted, perpetually depressed g...","[Hindi, Urdu, Gujarati, Panjabi]",{'$date': '2003-11-28T05:30:00.000+0530'},0,"[Niranjan Iyengar, Karan Johar]",[Nikkhil Advani],"[Shah Rukh Khan, Preity Zinta, Saif Ali Khan, ...",https://images-na.ssl-images-amazon.com/images...,"[Comedy, Drama, Romance]",{'$date': '2016-11-02T18:24:53.052+0530'},Kal Ho Naa Ho
4,{'$oid': '581994c50ad09b0701a0e72b'},7.6,tt3043252,'Parched' is a story about women set in the he...,"[Hindi, English]",{'$date': '2016-06-17T05:30:00.000+0530'},0,"[Supratik Sen, Leena Yadav]",[Leena Yadav],"[Tannishtha Chatterjee, Radhika Apte, Lehar Kh...",https://images-na.ssl-images-amazon.com/images...,[Drama],{'$date': '2016-11-02T18:24:53.572+0530'},Parched

## Chargement d'un fichier Excel

Les données peuvent également être stockées dans des fichiers **Excel**.

Dans cette étape nous allons :

- définir le chemin vers le fichier Excel
- charger une feuille spécifique avec `pd.read_excel()`
- convertir les données en DataFrame Pandas
- afficher les premières lignes pour vérifier le chargement des données

In [ ]:
# 1. Définition du chemin vers le fichier Excel
path_excel = "../data/Financial Sample (1).xlsx"

# 2. Chargement d'une feuille spécifique
df_gestion = pd.read_excel(path_excel, sheet_name='Sheet1')

# 3. Affichage des premières lignes pour vérification
print("Les données ont été chargées avec succès :")
display(df_gestion.head())

Les données ont été chargées avec succès :

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,NaN,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014

## Connexion à une base de données MySQL

Dans cette étape nous récupérons des données depuis une base de données relationnelle **MySQL**.

Nous utilisons la bibliothèque **SQLAlchemy** pour créer une connexion entre Python et la base de données.

Actions réalisées :

- création d'une connexion à la base MySQL
- exécution d'une requête SQL
- récupération des résultats dans un DataFrame Pandas
- affichage des étudiants ayant une note finale G3 supérieure à 15

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Création d'une connexion avec la base de données MySQL
engine = create_engine("mysql+pymysql://root:@localhost/school")

# Requête SQL pour sélectionner les étudiants ayant une note G3 > 15
query = "SELECT * FROM etudiants WHERE G3 > 15"

# stockage du résultat dans un DataFrame Pandas
df = pd.read_sql(query, engine)

# Affichage des 5 premières lignes
print("Apercu des etudiants(G3>15):")
display(df.head())

# Analyse statique des notes(G3)
print("les premieres statistiques descriptives des notes (G3):")
display(df.describe())

Apercu des etudiants(G3>15):

,COL 1,COL 2,COL 3,COL 4,COL 5,COL 6,COL 7,COL 8,COL 9,COL 10,...,COL 24,COL 25,COL 26,COL 27,COL 28,COL 29,COL 30,COL 31,COL 32,G3
0,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
1,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16
2,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,2,15,15,16
3,GP,M,15,U,GT3,T,4,4,services,services,...,4,3,1,1,1,5,0,17,16,17
4,GP,M,15,R,GT3,T,4,3,teacher,at_home,...,4,5,2,1,1,5,0,17,16,16

les premieres statistiques descriptives des notes (G3):

,COL 1,COL 2,COL 3,COL 4,COL 5,COL 6,COL 7,COL 8,COL 9,COL 10,...,COL 24,COL 25,COL 26,COL 27,COL 28,COL 29,COL 30,COL 31,COL 32,G3
count,40,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
unique,2,2,5,2,2,2,4,5,5,5,...,5,5,5,3,5,5,14,7,5,5
top,GP,M,16,U,GT3,T,4,4,services,other,...,4,3,2,1,1,5,0,16,18,16
freq,37,24,13,33,26,34,22,14,17,17,...,19,12,14,32,23,12,12,12,12,16

## Collecte de données par Web Scraping

Le **Web Scraping** consiste à extraire automatiquement des informations à partir de pages web.

Pour cela nous utilisons :

- `requests` pour envoyer des requêtes HTTP
- `BeautifulSoup` pour analyser le contenu HTML
- `pandas` pour organiser les données extraites

Web Scraping

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

### Vérification du fichier robots.txt

Avant de réaliser un scraping sur un site web, il est recommandé de consulter le fichier **robots.txt**.

Ce fichier indique quelles parties du site peuvent être explorées par des robots ou scripts automatisés.

In [ ]:
#verification du fichier robots.txt du site
url="https://books.toscrape.com/robots.txt"

#Envoi dune requete HTTP pour recuperer le fichier
reponse=requests.get(url)

#Affichage du contenu du fichier
print("Contenu du fichier:")
print(reponse.text)

Contenu du fichier:
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.21.6</center>
</body>
</html>

### Extraction des titres des livres

Dans cette étape nous analysons le contenu HTML de la page web.

Les actions réalisées sont :

- téléchargement du contenu HTML de la page
- analyse du HTML avec BeautifulSoup
- recherche des balises `<h3>` contenant les titres des livres
- stockage des titres dans une liste Python

In [ ]:
#Url du site
url="https://books.toscrape.com"

#Envoi de la requete vers le site
reponse=requests.get(url)

#Recuperation du contenu HTML de la page
html=reponse.text

#Creation de l`objet BeautifulSoup pour parser le html
soup=BeautifulSoup(html,"html.parser")

#Recherche de toutes les balises <h3> qui contiennent les titres
titres=soup.find_all("h3")
#Creation d`une liste pour stocker les titres
liste_titres=[]

#parcours des resultats 
for t in titres:
    titre=t.text
    liste_titres.append(titre)

#Affichage des titres
print("Liste des titres:")
print(liste_titres)

Liste des titres:
['A Light in the ...', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History ...', 'The Requiem Red', 'The Dirty Little Secrets ...', 'The Coming Woman: A ...', 'The Boys in the ...', 'The Black Maria', 'Starving Hearts (Triangular Trade ...', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little ...", 'Rip it Up and ...', 'Our Band Could Be ...', 'Olio', 'Mesaerion: The Best Science ...', 'Libertarianism for Beginners', "It's Only the Himalayas"]

### Transformation des données extraites

Les titres récupérés lors du Web Scraping sont stockés dans une liste Python.

Dans cette étape nous convertissons cette liste en **DataFrame Pandas** afin de faciliter l'analyse et la manipulation des données.

In [ ]:
#Creation d`une DataFrame avec les titres
df=pd.DataFrame(liste_titres, columns=["titre"])

#Affichage des 5 premiers lignes
display(df.head())

                          titre
0            A Light in the ...
1            Tipping the Velvet
2                    Soumission
3                 Sharp Objects
4  Sapiens: A Brief History ...

## Acquisition de données via une API

Les **API (Application Programming Interface)** permettent d'accéder à des données en ligne via des requêtes HTTP.

Dans cette étape nous allons :

- envoyer une requête à une API publique
- récupérer les données au format JSON
- convertir ces données en DataFrame Pandas
- afficher les premières lignes du dataset

In [ ]:
#url de l`API
api_url="https://jsonplaceholder.typicode.com/posts"

#Envoi de la requete vers l`API
reponse=requests.get(api_url)

#Conversation de la reponse en format JSON
data=reponse.json()

#Creation d`un DataFrame 
df=pd.DataFrame(data)

#Affichage des 5 premiers lignes
display(df.head())

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...